export const generationQueryKeys = {
  all: ['generations'] as const,
  byShot: (shotId: string) => ['all-shot-generations', shotId] as const,
  byShotAll: ['all-shot-generations'] as const,
  detail: (generationId: string) => ['generation', generationId] as const,
  detailAll: ['generation'] as const,
  meta: (shotId: string) => ['shot-generations-meta', shotId] as const,
  unpositionedCount: (shotId: string) => ['unpositioned-count', shotId] as const,
  variants: (generationId: string) => ['generation-variants', generationId] as const,
  variantsAll: ['generation-variants'] as const,
  variantBadges: ['variant-badges'] as const,
  derived: (generationId: string) => ['derived-items', generationId] as const,
  derivedAll: ['derived-items'] as const,
  derivedGenerations: (generationId: string) => ['derived-generations', generationId] as const,
  derivedGenerationsAll: ['derived-generations'] as const,
  byProject: (projectId: string) => ['project-generations', projectId] as const,
  byProjectAll: ['project-generations'] as const,
  lineageChain: (generationId: string) => ['lineage-chain', generationId] as const,
  lastVideo: (shotId: string) => ['last-video-generation', shotId] as const,
  forTask: (taskId: string) => ['image-generation-for-task', taskId] as const,
  videoForTask: (taskId: string) => ['video-generations-for-task', taskId] as const,
} as const;
