export const themeAnimations = {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
				'wes-float': 'wes-float 5s ease-in-out infinite',
				'wes-shimmer': 'wes-shimmer 2s infinite linear',
				'wes-appear': 'wes-appear 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both',
				'film-grain': 'film-grain 0.5s infinite',
				'vintage-scratches': 'vintage-scratches 8s infinite linear',
				'typewriter': 'typewriter 4s steps(44) 1s 1 normal both',
				'blink-caret': 'blink-caret .75s step-end infinite',
				'vintage-glow': 'vintage-glow 3s ease-in-out infinite',
				'subtle-wiggle': 'subtle-wiggle 2s ease-in-out infinite',
				'spin-left-fade': 'spin-left-fade 0.6s ease-out forwards',
				'spin-right-fade': 'spin-right-fade 0.6s ease-out forwards',
				'spin-left-fade-reverse': 'spin-left-fade-reverse 0.6s ease-out forwards',
				'spin-right-fade-reverse': 'spin-right-fade-reverse 0.6s ease-out forwards',
        'custom-fade-in': 'custom-fade-in 0.3s ease-out forwards',
        'gradient-shift': 'gradient-shift 12s ease-in-out infinite',
        'pulse-subtle': 'pulse-subtle 8s ease-in-out infinite',
        shimmer: 'shimmer 3s linear infinite',
        'float-slow': 'float-slow 20s ease-in-out infinite',
        'float-gentle': 'float-gentle 15s ease-in-out infinite',
        'rotate-gentle': 'rotate-gentle 25s ease-in-out infinite',
        'paintbrush-stroke': 'paintbrush-stroke 1.8s ease-in-out infinite',
        'paint-particle-1': 'paint-particle-sequential 1.8s ease-out infinite 0s',
        'paint-particle-2': 'paint-particle-sequential 1.8s ease-out infinite 0.7s',
        'paint-particle-3': 'paint-particle-sequential 1.8s ease-out infinite 0.9s',
        'paint-particle-fractal-1': 'paint-particle-sequential 1.8s ease-out infinite 0.1s',
        'paint-particle-fractal-2': 'paint-particle-sequential 1.8s ease-out infinite 0.2s',
        'paint-particle-fractal-3': 'paint-particle-sequential 1.8s ease-out infinite 0.3s',
        'paint-particle-fractal-4': 'paint-particle-sequential 1.8s ease-out infinite 0.4s',
        'paint-particle-fractal-5': 'paint-particle-sequential 1.8s ease-out infinite 0.5s',
        'paint-particle-fractal-6': 'paint-particle-sequential 1.8s ease-out infinite 0.6s',
        'paper-plane-glide-1': 'paper-plane-glide-1 25s ease-in-out infinite',
        'paper-plane-loop': 'paper-plane-loop 30s ease-in-out infinite',
        'paper-plane-swoop': 'paper-plane-swoop 35s ease-in-out infinite',
        'paper-plane-figure8': 'paper-plane-figure8 40s ease-in-out infinite',
        'paper-plane-diagonal-tl-br': 'paper-plane-diagonal-tl-br 15s linear infinite',
        'paper-plane-diagonal-tr-bl': 'paper-plane-diagonal-tr-bl 15s linear infinite',
        'paper-plane-diagonal-bl-tr': 'paper-plane-diagonal-bl-tr 15s linear infinite',
        'paper-plane-diagonal-br-tl': 'paper-plane-diagonal-br-tl 15s linear infinite',
        'paper-plane-horizontal-lr': 'paper-plane-horizontal-lr 20s ease-in-out infinite',
        'paper-plane-horizontal-rl': 'paper-plane-horizontal-rl 20s ease-in-out infinite',
        'paper-plane-vertical-tb': 'paper-plane-vertical-tb 18s ease-in-out infinite',
        'paper-plane-vertical-bt': 'paper-plane-vertical-bt 18s ease-in-out infinite',
        'paper-plane-spiral-cw': 'paper-plane-spiral-cw 25s ease-out infinite',
        'paper-plane-spiral-ccw': 'paper-plane-spiral-ccw 25s ease-out infinite',
        'paper-plane-zigzag-h': 'paper-plane-zigzag-h 22s ease-in-out infinite',
        'paper-plane-zigzag-v': 'paper-plane-zigzag-v 22s ease-in-out infinite',
        'brain-pulse': 'brain-pulse 2s ease-in-out infinite',
        'subtle-bob': 'subtle-bob 1.5s ease-in-out infinite',
        'gifting-motion': 'gifting-motion 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'pulse-breathe': 'pulse-breathe 3s ease-in-out infinite',
        'pulse-wave': 'pulse-wave 2.5s ease-in-out infinite',
        'pulse-sweep': 'pulse-sweep 2s ease-out infinite',
} as const;
