/** Generated from contract/openapi/workspace-v1.yaml; do not edit by hand. */
export const PROTOCOL = "workspace.v1" as const;
export type HeadersLike = Record<string, string>;
export type Transport = (method: string, path: string, headers: HeadersLike, body?: Uint8Array) => Promise<{ status: number; headers: HeadersLike; body: Uint8Array }>;
export interface Health { status: "ok" | "degraded"; protocol: typeof PROTOCOL; schema_digest: string; runtime_epoch: number }
export interface Handshake { protocol: typeof PROTOCOL; schema_digest: string; session_id: string; actor_id: string; realm_id: string; scopes: string[] }
export interface Realm { realm_id: string; display_name: string; version: number; created_at: string; state?: "active" | "tombstoned"; tombstoned_at?: string | null; lifecycle_version?: number }
export interface IntegrityCheck { ok: boolean; [key: string]: unknown }
export interface IntegrityReport { state: "ready" | "unhealthy"; ok: boolean; schema_version: number; recovery_action: string; issues?: string[]; checks: Record<string, IntegrityCheck> }
export interface RealmLifecycle { realm_id: string; state: "active" | "tombstoned"; version: number; tombstoned_at?: string | null; reason?: string | null }
export interface Project { project_id: string; realm_id: string; slug: string; name: string; metadata: Record<string, unknown>; version: number; created_at: string; updated_at: string; archived?: boolean }
export interface ProjectDocument { document_id: string; project_id: string; kind: string; content: unknown; version: number; created_at: string; updated_at: string }
export interface Generation { generation_id: string; project_id: string; source_task_id?: string | null; type: string; status: string; metadata: Record<string, unknown>; version: number; created_at: string; updated_at: string }
export interface GenerationVariant { variant_id: string; generation_id: string; object_id?: string | null; variant_type: string; metadata: Record<string, unknown>; created_at: string }
export interface ManagedObject { object_id: string; digest: string; media_type: string; size: number; version: number; created_at: string; filename?: string; relation?: string }
export type ManagedOutputDurability = "durable" | "temporary";
export type ManagedCoverageMode = "interval" | "clips" | "cuts" | "shots";
export interface ManagedOutput { association_id: string; project_id: string | null; run_id: string; task_id: string; attempt_id: string; output_port: string; group_key: string; variant_key: string; selector: { group_key: string; variant_key: string }; object_id: string; digest: string; manifest_ref: string | null; size: number; filename: string; media_type: string; ordinal: number; role: string; producer: Record<string, unknown>; provenance: Record<string, unknown>; durability: ManagedOutputDurability; regeneration?: Record<string, unknown> | null; coverage?: Record<string, unknown> | null; state: string; version: number; lifecycle: Record<string, unknown>; [key: string]: unknown }
export interface ManagedOutputAdoption { association_id?: string; manifest_ref?: string | null; object_id?: string; digest?: string; size?: number; filename?: string; media_type?: string; output_port?: string; selector?: Record<string, unknown>; ordinal?: number; role?: string; durability?: ManagedOutputDurability }
export interface ManagedOutputLifecycle { operation: "lease" | "release" | "pin" | "unpin" | "expire" | "reclaim" | "promote"; expected_version: number; lease_id?: string; lease_owner?: string; lease_seconds?: number; provenance?: Record<string, unknown> }
export interface ShotTextBinding { binding_id: string; project_id: string; shot_id: string; kind: "prompt" | "voiceover_script" | "transcript"; slot?: string | null; media_id: string; event_stream_id: string; head: number; content_hash: string; mime_type: string; byte_size: number; created_at: string; updated_at: string }
export interface MediaRelation { project_id: string; from_object_id: string; to_object_id: string; kind: "derived_from" | "variant_of" | "uses_as_input" | "mask_for" | "audio_for"; ordinal: number; metadata: Record<string, unknown>; created_at: string }
export interface ByteResponse { data: Uint8Array; status: number; headers: HeadersLike; etag?: string; content_range?: string }
export type TaskState = "queued" | "ready" | "running" | "succeeded" | "failed" | "cancel_requested" | "cancelled" | "retrying";
export interface StorageEstimate { scratch_bytes: number; output_bytes: number }
export interface ExactFacts { interpreter?: string; runtime_lock?: string; engine_lock?: string; model_digest?: string; custom_node_digest?: string; driver?: string; root?: string; port?: string | number }
export interface MinimumFacts { vram_bytes?: number; scratch_bytes?: number }
export interface ExecutionFacts { exact?: ExactFacts; minimum?: MinimumFacts }
export interface Task { task_id: string; run_id: string; project_id: string | null; state: TaskState; version: number; capability_id: string; capability_digest: string; idempotency_key: string; created_at: string; updated_at: string; attempt_id?: string | null; runtime_epoch: number; input_object_ids: string[]; spec: Record<string, unknown>; generation_intent?: Record<string, unknown>; required_facts?: ExecutionFacts; storage_estimate?: StorageEstimate; result?: Record<string, unknown> | null }
export interface AttemptFence { attempt_id: string; task_id: string; project_id: string | null; lease_id: string; fence: number; runtime_epoch: number; input_object_ids: string[]; spec: Record<string, unknown>; generation_intent?: Record<string, unknown>; expected_effect?: Record<string, unknown>; required_facts?: ExecutionFacts; storage_estimate?: StorageEstimate }
export interface ClaimWaiting { task: Task; waiting_reason: "waiting_for_worker" | "capability_unavailable" | "insufficient_storage" | "waiting_for_gpu" | "waiting_for_cpu" | "waiting_for_network" | "waiting_for_executor_facts" }
export interface RecoveryAuthorization { attempt_id: string; task_id: string; executor_id: string; runtime_epoch: number; nonce: string; expires_in_seconds: number }
export interface RecoveryCheckpointReceipt { checkpoint_id: string; attempt_id: string; task_id: string; runtime_epoch: number; nonce: string; digest: string; size: number; state: string; path?: string }
export interface RecoveryReceipt { type: string; checkpoint_id: string; attempt_id: string; task_id: string; runtime_epoch: number; command: string; status: string; version?: number; checkpoint_digest?: string; executor_result?: unknown; checkpoint?: unknown; error?: { type: string; message: string } }
export interface RecoveryResumeReceipt { receipt: RecoveryReceipt; attempt: AttemptFence }
export interface MutationReceipt { receipt_id: string; command_kind: string; idempotency_key: string; request_hash: string; project_id: string; project_seq: [number, number]; event_ids: string[]; result: unknown; created_at: string }
export type MutationResult<T> = T & { readonly receipt: MutationReceipt }
export interface Event { event_id: string; sequence: number; cursor: string; event_type: string; aggregate_type: string; aggregate_id: string; payload: Record<string, unknown>; occurred_at: string }
export interface EventPage { items: Event[]; next_cursor: string | null }
export interface Page<T> { items: T[]; next_cursor: string | null }
export type CapabilityStatus = "ready" | "unavailable" | "unsupported" | "retired";
export interface Capability { capability_id: string; definition_digest: string; status: CapabilityStatus; required_resource_keys: string[]; estimated_scratch_bytes: number; estimated_output_bytes: number; unavailable_reason?: string | null }
export interface Executor { executor_id: string; max_concurrency: number; resource_keys: string[]; capabilities: Capability[]; protocol: typeof PROTOCOL; runtime_epoch?: number; source_digest?: string | null; dependency_digest?: string | null; source_epoch?: string | null; verified_facts?: ExecutionFacts }
export class ApiError extends Error { constructor(public status: number, public code: string, message: string, public request_id = "", public details: Record<string, unknown> = {}) { super(`${code}: ${message}`); this.name = "ApiError" } }

export class WorkspaceClient {
  public handshakeInfo?: Handshake;
  constructor(private readonly baseUrl: string, private readonly token?: string, private readonly transport?: Transport) {}
  private async request(method: string, path: string, body?: Uint8Array, headers: HeadersLike = {}, expected = [200]): Promise<{ status: number; headers: HeadersLike; body: Uint8Array }> {
    const requestHeaders: HeadersLike = { Accept: "application/json", ...headers };
    if (this.token) requestHeaders.Authorization ??= `Bearer ${this.token}`;
    let response: { status: number; headers: HeadersLike; body: Uint8Array };
    if (this.transport) response = await this.transport(method, path, requestHeaders, body);
    else {
      const responseObj = await fetch(`${this.baseUrl.replace(/\/$/, "")}${path}`, { method, headers: requestHeaders, body: body as BodyInit | undefined });
      const bytes = new Uint8Array(await responseObj.arrayBuffer());
      const responseHeaders: HeadersLike = {}; responseObj.headers.forEach((value, key) => { responseHeaders[key] = value });
      response = { status: responseObj.status, headers: responseHeaders, body: bytes };
    }
    if (!expected.includes(response.status)) throw this.decodeError(response.status, response.body);
    return response;
  }
  private decodeError(status: number, body: Uint8Array): ApiError { try { const v = JSON.parse(new TextDecoder().decode(body)); return new ApiError(status, v.code ?? "http_error", v.message ?? `HTTP ${status}`, v.request_id ?? "", v.details ?? {}) } catch { return new ApiError(status, "http_error", `HTTP ${status}`) } }
  private json<T>(body: Uint8Array): T { return JSON.parse(new TextDecoder().decode(body)) as T }
  private page<T>(body: Uint8Array): Page<T> { const value = this.json<Partial<Page<T>>>(body); if (!Array.isArray(value.items) || !(value.next_cursor === null || typeof value.next_cursor === "string")) throw new Error("invalid page response: items and next_cursor are required"); return value as Page<T> }
  private mutation<T>(body: Uint8Array): MutationResult<T> { const value = this.json<Record<string, unknown>>(body); if (!("data" in value) || !("receipt" in value) || !value.receipt || typeof value.data !== "object" || value.data === null) throw new Error("invalid mutation response: committed receipt is required"); const data = value.data as Record<string, unknown>; Object.defineProperty(data, "receipt", { value: value.receipt, enumerable: false, writable: false, configurable: false }); return data as MutationResult<T> }
  async health(): Promise<Health> { return this.json<Health>((await this.request("GET", "/v1/health")).body) }
  async handshake(client_name: string, client_version: string, requested_scopes: string[]): Promise<Handshake> { const v = this.json<Handshake>((await this.request("POST", "/v1/handshake", new TextEncoder().encode(JSON.stringify({ protocol: PROTOCOL, client_name, client_version, requested_scopes })), { "Content-Type": "application/json" })).body); this.handshakeInfo = v; return v }
  async getRealm(): Promise<Realm> { return this.json<Realm>((await this.request("GET", "/v1/realm")).body) }
  async doctor(): Promise<IntegrityReport> { return this.json<IntegrityReport>((await this.request("GET", "/v1/doctor")).body) }
  async createBackup(destination: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", "/v1/backup", new TextEncoder().encode(JSON.stringify({ destination })), { "Content-Type": "application/json" }, [200, 201])).body) }
  async restoreBackup(backup: string, destination: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", "/v1/restore", new TextEncoder().encode(JSON.stringify({ backup, destination })), { "Content-Type": "application/json" }, [200, 201])).body) }
  async exportRealm(): Promise<Record<string, unknown>> { return this.json((await this.request("GET", "/v1/export")).body) }
  async tombstoneRealm(reason?: string, expectedVersion?: number): Promise<RealmLifecycle> { const payload: Record<string, unknown> = {}; if (reason !== undefined) payload.reason = reason; if (expectedVersion !== undefined) payload.expected_version = expectedVersion; return this.json<RealmLifecycle>((await this.request("POST", "/v1/realm/tombstone", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async recoverRealm(expectedRealmId?: string, expectedVersion?: number, confirmation?: string, noninteractive = false): Promise<RealmLifecycle> { const payload: Record<string, unknown> = {}; if (expectedRealmId !== undefined) payload.expected_realm_id = expectedRealmId; if (expectedVersion !== undefined) payload.expected_version = expectedVersion; if (confirmation !== undefined) payload.confirmation = confirmation; if (noninteractive) payload.noninteractive = true; return this.json<RealmLifecycle>((await this.request("POST", "/v1/realm/recover", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async purgeRealm(confirmation: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", "/v1/realm/purge", new TextEncoder().encode(JSON.stringify({ confirmation })), { "Content-Type": "application/json" })).body) }
  async createProject(name: string, idempotencyKey: string, slug?: string, metadata?: Record<string, unknown>): Promise<MutationResult<Project>> { const payload: Record<string, unknown> = { name }; if (slug !== undefined) payload.slug = slug; if (metadata !== undefined) payload.metadata = metadata; return this.mutation<Project>((await this.request("POST", "/v1/projects", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getProject(projectId: string): Promise<Project> { return this.json<Project>((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}`)).body) }
  async updateProject(projectId: string, idempotencyKey: string, expectedVersion?: number, name?: string, metadata?: Record<string, unknown>): Promise<Project> { const payload: Record<string, unknown> = {}; if (expectedVersion !== undefined) payload.expected_version = expectedVersion; if (name !== undefined) payload.name = name; if (metadata !== undefined) payload.metadata = metadata; return this.json<Project>((await this.request("PATCH", `/v1/projects/${encodeURIComponent(projectId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async createDocument(projectId: string, documentId: string, kind: string, content: unknown, idempotencyKey: string): Promise<MutationResult<ProjectDocument>> { return this.mutation<ProjectDocument>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/documents`, new TextEncoder().encode(JSON.stringify({ document_id: documentId, kind, content })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async listDocuments(projectId: string, cursor?: string, limit = 50): Promise<Page<ProjectDocument>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/documents?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getDocument(projectId: string, documentId: string): Promise<ProjectDocument> { return this.json<ProjectDocument>((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}`)).body) }
  async updateDocument(projectId: string, documentId: string, expectedVersion: number, idempotencyKey: string, content?: unknown, kind?: string): Promise<MutationResult<ProjectDocument>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (content !== undefined) payload.content = content; if (kind !== undefined) payload.kind = kind; return this.mutation<ProjectDocument>((await this.request("PATCH", `/v1/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async listProjects(cursor?: string, limit = 50): Promise<Page<Project>> { return this.page((await this.request("GET", `/v1/projects?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async selectProject(project: string, scope: "workspace" | "user" = "workspace", idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation<Record<string, unknown>>((await this.request("PUT", "/v1/projects/selection", new TextEncoder().encode(JSON.stringify({ project, scope })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async currentProject(): Promise<Record<string, unknown>> { return this.json((await this.request("GET", "/v1/projects/selection")).body) }
  async createTimeline(projectId: string, timelineId: string, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/timelines`, new TextEncoder().encode(JSON.stringify({ timeline_id: timelineId })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async createTimelineDocument(projectId: string, timelineId: string, config: Record<string, unknown>, registry: Record<string, unknown>, idempotencyKey: string, slug?: string | null, name?: string | null): Promise<MutationResult<Record<string, unknown>>> {
    const payload = { timeline_id: timelineId, slug: slug ?? timelineId, name: name ?? slug ?? timelineId, config, registry };
    return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/timeline-documents`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [201])).body);
  }
  async updateTimelineDocument(projectId: string, timelineId: string, expectedVersion: number, idempotencyKey: string, config: Record<string, unknown>, registry: Record<string, unknown>, slug?: string, name?: string): Promise<MutationResult<Record<string, unknown>>> {
    const current = await this.getDocument(projectId, `timeline:${timelineId}`);
    const content: Record<string, unknown> = { ...(current.content as Record<string, unknown>), config, registry };
    if (slug !== undefined) content.slug = slug;
    if (name !== undefined) content.name = name;
    const document = await this.updateDocument(projectId, `timeline:${timelineId}`, expectedVersion, idempotencyKey, content);
    const timeline = await this.getTimeline(timelineId);
    return Object.assign({ ...timeline, slug: content.slug ?? timelineId, name: content.name ?? timelineId, config_version: document.version, config, registry }, { receipt: document.receipt }) as MutationResult<Record<string, unknown>>;
  }
  async listTimelines(projectId: string, cursor?: string, limit = 50): Promise<Page<Record<string, unknown>>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/timelines?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getTimeline(timelineId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/timelines/${encodeURIComponent(timelineId)}`)).body) }
  async listTimelineHistory(timelineId: string, cursor?: string, limit = 50): Promise<Page<Record<string, unknown>>> { return this.page((await this.request("GET", `/v1/timelines/${encodeURIComponent(timelineId)}/history?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async diffTimeline(timelineId: string, fromVersion: number, toVersion: number): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/timelines/${encodeURIComponent(timelineId)}/diff?from_version=${fromVersion}&to_version=${toVersion}`)).body) }
  async archiveTimeline(timelineId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverTimeline(timelineId: string, expectedVersion: number, version: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion, version })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async updateTimeline(timelineId: string, expectedVersion: number, idempotencyKey: string, shots?: Record<string, unknown>[], references?: Record<string, unknown>[]): Promise<MutationResult<Record<string, unknown>>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (shots !== undefined) payload.shots = shots; if (references !== undefined) payload.references = references; return this.mutation((await this.request("PATCH", `/v1/timelines/${encodeURIComponent(timelineId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async createShot(timelineId: string, shot: Record<string, unknown>, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/shots`, new TextEncoder().encode(JSON.stringify(shot)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getShot(shotId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/shots/${encodeURIComponent(shotId)}`)).body) }
  async listProjectShots(projectId: string, cursor?: string, limit = 50, includeArchived = false): Promise<Page<Record<string, unknown>>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/shots?limit=${limit}&include_archived=${includeArchived}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async createProjectShot(projectId: string, shot: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shots`, new TextEncoder().encode(JSON.stringify(shot)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getProjectShot(projectId: string, shotId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}`)).body) }
  async updateProjectShot(projectId: string, shotId: string, expectedVersion: number, name: string | undefined, metadata: Record<string, unknown> | undefined, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (name !== undefined) payload.name = name; if (metadata !== undefined) payload.metadata = metadata; return this.mutation((await this.request("PATCH", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async archiveProjectShot(projectId: string, shotId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverProjectShot(projectId: string, shotId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async addShotItem(projectId: string, shotId: string, item: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}/items`, new TextEncoder().encode(JSON.stringify(item)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async promoteProjectShotCandidate(projectId: string, shotId: string, candidateItemId: string, expectedHeadSeq: number, idempotencyKey: string, timelineAssets: Record<string, unknown>[] = []): Promise<MutationResult<Record<string, unknown>>> { const payload: Record<string, unknown> = { candidate_item_id: candidateItemId, expected_head_seq: expectedHeadSeq }; if (timelineAssets.length) payload.timeline_assets = timelineAssets; return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}/promote-candidate`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async removeShotItem(projectId: string, shotId: string, itemId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("DELETE", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}/items/${encodeURIComponent(itemId)}`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async reorderShotItems(projectId: string, shotId: string, itemIds: string[], expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shots/${encodeURIComponent(shotId)}/reorder`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion, item_ids: itemIds })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async listProjectShotTextBindings(projectId: string, shotId?: string, kind?: string, slot?: string): Promise<Page<ShotTextBinding>> { const query = new URLSearchParams(); if (shotId !== undefined) query.set("shot_id", shotId); if (kind !== undefined) query.set("kind", kind); if (slot !== undefined) query.set("slot", slot); const suffix = query.toString() ? `?${query.toString()}` : ""; return this.page<ShotTextBinding>((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/shot-text-bindings${suffix}`)).body) }
  async getProjectShotTextBinding(projectId: string, bindingId: string): Promise<ShotTextBinding> { return this.json<ShotTextBinding>((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/shot-text-bindings/${encodeURIComponent(bindingId)}`)).body) }
  async setProjectShotTextBinding(projectId: string, body: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<ShotTextBinding>> { return this.mutation<ShotTextBinding>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shot-text-bindings`, new TextEncoder().encode(JSON.stringify(body)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async setProjectShotTextBindingById(projectId: string, bindingId: string, body: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<ShotTextBinding>> { return this.mutation<ShotTextBinding>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shot-text-bindings/${encodeURIComponent(bindingId)}`, new TextEncoder().encode(JSON.stringify(body)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async rebindProjectShotTextBinding(projectId: string, bindingId: string, mediaId: string, expectedHead: number, idempotencyKey: string): Promise<MutationResult<ShotTextBinding>> { return this.mutation<ShotTextBinding>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/shot-text-bindings/${encodeURIComponent(bindingId)}/rebind`, new TextEncoder().encode(JSON.stringify({ media_id: mediaId, expected_head: expectedHead })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async updateShot(shotId: string, expectedVersion: number, startMs?: number, durationMs?: number, referenceIds?: string[], idempotencyKey?: string): Promise<Record<string, unknown>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (startMs !== undefined) payload.start_ms = startMs; if (durationMs !== undefined) payload.duration_ms = durationMs; if (referenceIds !== undefined) payload.reference_ids = referenceIds; const headers: HeadersLike = { "Content-Type": "application/json" }; if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey; return this.json((await this.request("PATCH", `/v1/shots/${encodeURIComponent(shotId)}`, new TextEncoder().encode(JSON.stringify(payload)), headers)).body) }
  async archiveShot(shotId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/shots/${encodeURIComponent(shotId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverShot(shotId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/shots/${encodeURIComponent(shotId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async createReference(timelineId: string, reference: Record<string, unknown>, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/references`, new TextEncoder().encode(JSON.stringify(reference)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getReference(referenceId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/references/${encodeURIComponent(referenceId)}`)).body) }
  async listProjectReferences(projectId: string, cursor?: string, limit = 50, includeArchived = false): Promise<Page<Record<string, unknown>>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/references?limit=${limit}&include_archived=${includeArchived}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async createProjectReference(projectId: string, reference: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/references`, new TextEncoder().encode(JSON.stringify(reference)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getProjectReference(projectId: string, referenceId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/references/${encodeURIComponent(referenceId)}`)).body) }
  async updateProjectReference(projectId: string, referenceId: string, expectedVersion: number, name: string | undefined, description: string | undefined, metadata: Record<string, unknown> | undefined, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (name !== undefined) payload.name = name; if (description !== undefined) payload.description = description; if (metadata !== undefined) payload.metadata = metadata; return this.mutation((await this.request("PATCH", `/v1/projects/${encodeURIComponent(projectId)}/references/${encodeURIComponent(referenceId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async archiveProjectReference(projectId: string, referenceId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/references/${encodeURIComponent(referenceId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverProjectReference(projectId: string, referenceId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/references/${encodeURIComponent(referenceId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async associateReference(projectId: string, referenceId: string, association: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/references/${encodeURIComponent(referenceId)}/associations`, new TextEncoder().encode(JSON.stringify(association)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async setPrimaryReference(projectId: string, referenceId: string, associationId: string, expectedVersion: number, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/references/${encodeURIComponent(referenceId)}/primary`, new TextEncoder().encode(JSON.stringify({ association_id: associationId, expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async linkReferences(projectId: string, link: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<Record<string, unknown>>> { return this.mutation((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/reference-links`, new TextEncoder().encode(JSON.stringify(link)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async updateReference(referenceId: string, expectedVersion: number, objectId?: string, role?: string, idempotencyKey?: string): Promise<Record<string, unknown>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (objectId !== undefined) payload.object_id = objectId; if (role !== undefined) payload.role = role; const headers: HeadersLike = { "Content-Type": "application/json" }; if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey; return this.json((await this.request("PATCH", `/v1/references/${encodeURIComponent(referenceId)}`, new TextEncoder().encode(JSON.stringify(payload)), headers)).body) }
  async archiveReference(referenceId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/references/${encodeURIComponent(referenceId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverReference(referenceId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/references/${encodeURIComponent(referenceId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async ingestObject(data: Uint8Array, mediaType: string, idempotencyKey: string, filename?: string): Promise<MutationResult<ManagedObject>> { const headers: HeadersLike = { "Content-Type": mediaType, "Idempotency-Key": idempotencyKey }; if (filename) headers["X-Filename"] = filename; return this.mutation<ManagedObject>((await this.request("POST", "/v1/objects", data, headers, [200, 201])).body) }
  async ingestProjectObject(projectId: string, data: Uint8Array, mediaType: string, idempotencyKey: string, filename?: string): Promise<MutationResult<ManagedObject>> { const headers: HeadersLike = { "Content-Type": mediaType, "Idempotency-Key": idempotencyKey }; if (filename) headers["X-Original-Name"] = filename; return this.mutation<ManagedObject>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/objects`, data, headers, [200, 201])).body) }
  async listProjectObjects(projectId: string, cursor?: string, limit = 50): Promise<Page<ManagedObject>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/objects?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async createMediaRelation(projectId: string, fromObjectId: string, toObjectId: string, kind: MediaRelation["kind"], idempotencyKey: string, metadata: Record<string, unknown> = {}, ordinal = 0): Promise<MutationResult<MediaRelation>> { const payload: Record<string, unknown> = { from_object_id: fromObjectId, to_object_id: toObjectId, kind, metadata }; if (ordinal) payload.ordinal = ordinal; return this.mutation<MediaRelation>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/media-relations`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async listMediaRelations(projectId: string, cursor?: string, limit = 50): Promise<Page<MediaRelation>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/media-relations?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getObject(objectId: string, byteRange?: [number, number?]): Promise<ByteResponse> { const headers: HeadersLike = {}; if (byteRange) { if (byteRange[0] < 0 || (byteRange[1] !== undefined && byteRange[1] < byteRange[0])) throw new Error("invalid byte range"); headers.Range = `bytes=${byteRange[0]}-${byteRange[1] ?? ""}` } const r = await this.request("GET", `/v1/objects/${encodeURIComponent(objectId)}`, undefined, headers, [200, 206]); return { data: r.body, status: r.status, headers: r.headers, etag: r.headers.ETag ?? r.headers.etag, content_range: r.headers["Content-Range"] ?? r.headers["content-range"] } }
  async headObject(objectId: string, byteRange?: [number, number?]): Promise<ByteResponse> { const headers: HeadersLike = {}; if (byteRange) headers.Range = `bytes=${byteRange[0]}-${byteRange[1] ?? ""}`; const r = await this.request("HEAD", `/v1/objects/${encodeURIComponent(objectId)}`, undefined, headers, [200, 206]); return { data: r.body, status: r.status, headers: r.headers, etag: r.headers.ETag ?? r.headers.etag, content_range: r.headers["Content-Range"] ?? r.headers["content-range"] } }
  async listManagedOutputs(taskId: string, cursor?: string, limit = 50): Promise<Page<ManagedOutput>> { return this.page<ManagedOutput>((await this.request("GET", `/v1/tasks/${encodeURIComponent(taskId)}/managed-outputs?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getManagedOutput(associationId: string): Promise<ManagedOutput> { return this.json<ManagedOutput>((await this.request("GET", `/v1/managed-outputs/${encodeURIComponent(associationId)}`)).body) }
  async adoptManagedOutput(associationId: string, idempotencyKey: string, body: ManagedOutputAdoption = {}): Promise<MutationResult<ManagedOutput>> { return this.mutation<ManagedOutput>((await this.request("POST", `/v1/managed-outputs/${encodeURIComponent(associationId)}/adopt`, new TextEncoder().encode(JSON.stringify(body)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async updateManagedOutputLifecycle(associationId: string, body: ManagedOutputLifecycle, idempotencyKey: string): Promise<MutationResult<ManagedOutput>> { return this.mutation<ManagedOutput>((await this.request("POST", `/v1/managed-outputs/${encodeURIComponent(associationId)}/lifecycle`, new TextEncoder().encode(JSON.stringify(body)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async admitTask(input: { capability_id: string; capability_digest: string; input_object_ids: string[]; schema_version?: string; settlement_effect?: Record<string, unknown>; project?: string; spec?: Record<string, unknown>; generation_intent?: Record<string, unknown>; storage_estimate?: StorageEstimate; required_facts?: ExecutionFacts }, idempotencyKey: string): Promise<MutationResult<Task>> { return this.mutation<Task>((await this.request("POST", "/v1/tasks", new TextEncoder().encode(JSON.stringify({ schema_version: "1", ...input })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getTask(taskId: string): Promise<Task> { return this.json<Task>((await this.request("GET", `/v1/tasks/${encodeURIComponent(taskId)}`)).body) }
  async listProjectTasks(projectId: string, cursor?: string, limit = 50): Promise<Page<Task>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/tasks?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async claimTask(executorId: string, capabilityIds: string[], idempotencyKey: string, runtimeEpoch: number): Promise<AttemptFence | ClaimWaiting | undefined> { const payload = { executor_id: executorId, capability_ids: capabilityIds, runtime_epoch: runtimeEpoch }; const r = await this.request("POST", "/v1/tasks/claim", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 204]); if (r.status === 204) return undefined; const value = this.json<AttemptFence | ClaimWaiting>(r.body); return "waiting_reason" in value ? value as ClaimWaiting : value as AttemptFence }
  async cancelTask(taskId: string, idempotencyKey: string, expectedVersion?: number): Promise<MutationResult<Task>> { return this.transitionTask(taskId, "cancel", idempotencyKey, expectedVersion) }
  async retryTask(taskId: string, idempotencyKey: string, expectedVersion?: number): Promise<MutationResult<Task>> { return this.transitionTask(taskId, "retry", idempotencyKey, expectedVersion) }
  private async transitionTask(taskId: string, action: "cancel" | "retry", idempotencyKey: string, expectedVersion?: number): Promise<MutationResult<Task>> { return this.mutation<Task>((await this.request("POST", `/v1/tasks/${encodeURIComponent(taskId)}/${action}`, new TextEncoder().encode(JSON.stringify(expectedVersion === undefined ? {} : { expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async getRun(runId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/runs/${encodeURIComponent(runId)}`)).body) }
  async cancelRun(runId: string, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/runs/${encodeURIComponent(runId)}/cancel`, new TextEncoder().encode("{}"), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async retryRun(runId: string, idempotencyKey: string, selectedTaskIds?: string[]): Promise<Record<string, unknown>> { const payload = selectedTaskIds === undefined ? {} : { selected_task_ids: selectedTaskIds }; return this.json((await this.request("POST", `/v1/runs/${encodeURIComponent(runId)}/retry`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async listProjectRuns(projectId: string, cursor?: string, limit = 50): Promise<Page<Record<string, unknown>>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/runs?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async listRunEvents(runId: string, cursor?: string, limit = 50): Promise<EventPage> { const query = cursor || limit !== 50 ? `?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}` : ""; return this.page<Event>((await this.request("GET", `/v1/runs/${encodeURIComponent(runId)}/events${query}`)).body) }
  async listEvents(cursor?: string, limit = 50, aggregateId?: string): Promise<Page<Event>> { const query = `/v1/events?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}${aggregateId ? `&aggregate_id=${encodeURIComponent(aggregateId)}` : ""}`; return this.page((await this.request("GET", query)).body) }
  async registerExecutor(executor: Executor, idempotencyKey: string): Promise<Executor> { return this.json<Executor>((await this.request("POST", "/v1/executors", new TextEncoder().encode(JSON.stringify(executor)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async listCapabilities(cursor?: string, limit = 50): Promise<Page<Capability>> { return this.page<Capability>((await this.request("GET", `/v1/capabilities?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async registerCapability(capability: Omit<Capability, "status" | "required_resource_keys" | "estimated_scratch_bytes" | "estimated_output_bytes"> & Partial<Pick<Capability, "status" | "required_resource_keys" | "estimated_scratch_bytes" | "estimated_output_bytes">>, idempotencyKey?: string): Promise<Capability> { const headers: HeadersLike = { "Content-Type": "application/json" }; if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey; return this.json<Capability>((await this.request("POST", "/v1/capabilities", new TextEncoder().encode(JSON.stringify({ status: "ready", required_resource_keys: [], estimated_scratch_bytes: 0, estimated_output_bytes: 0, ...capability })), headers, [200, 201])).body) }
  async settleAttempt(attemptId: string, settlement: Record<string, unknown>, idempotencyKey: string): Promise<MutationResult<Task>> { return this.mutation<Task>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/settle`, new TextEncoder().encode(JSON.stringify(settlement)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async failAttempt(attemptId: string, leaseId: string, fence: number, error: unknown, runtimeEpoch: number, idempotencyKey: string): Promise<MutationResult<Task>> { return this.mutation<Task>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/fail`, new TextEncoder().encode(JSON.stringify({ lease_id: leaseId, fence, runtime_epoch: runtimeEpoch, error })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async heartbeatAttempt(attemptId: string, leaseId: string, fence: number, idempotencyKey: string, runtimeEpoch: number): Promise<MutationResult<AttemptFence>> { const payload = { lease_id: leaseId, fence, runtime_epoch: runtimeEpoch }; return this.mutation<AttemptFence>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/heartbeat`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async prepareReboot(attemptId: string, leaseId: string, fence: number, runtimeEpoch: number): Promise<RecoveryAuthorization> { const payload = { lease_id: leaseId, fence, runtime_epoch: runtimeEpoch }; return this.json<RecoveryAuthorization>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/prepare-reboot`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async checkpointAttempt(attemptId: string, leaseId: string, fence: number, nonce: string, authorization: string, runtimeEpoch: number, state: Record<string, unknown> = {}): Promise<RecoveryCheckpointReceipt> { const payload = { lease_id: leaseId, fence, nonce, authorization, state, runtime_epoch: runtimeEpoch }; return this.json<RecoveryCheckpointReceipt>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/checkpoint`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" }, [200, 201])).body) }
  async requestReboot(checkpointId: string, nonce: string, authorization: string, runtimeEpoch: number, command = "reboot"): Promise<RecoveryReceipt> { return this.json<RecoveryReceipt>((await this.request("POST", "/v1/recovery/reboot", new TextEncoder().encode(JSON.stringify({ checkpoint_id: checkpointId, nonce, authorization, runtime_epoch: runtimeEpoch, command })), { "Content-Type": "application/json" })).body) }
  async resumeAttempt(checkpointId: string, nonce: string, authorization: string, runtimeEpoch: number): Promise<RecoveryResumeReceipt> { return this.json<RecoveryResumeReceipt>((await this.request("POST", "/v1/recovery/resume", new TextEncoder().encode(JSON.stringify({ checkpoint_id: checkpointId, nonce, authorization, runtime_epoch: runtimeEpoch })), { "Content-Type": "application/json" })).body) }
  async listGenerations(projectId: string, cursor?: string, limit = 50): Promise<Page<Generation>> { return this.page((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/generations?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async createGeneration(projectId: string, generationId: string, idempotencyKey: string, metadata: Record<string, unknown> = {}, type = "generation", sourceTaskId?: string): Promise<MutationResult<Generation>> { const payload: Record<string, unknown> = { generation_id: generationId, metadata, type }; if (sourceTaskId !== undefined) payload.source_task_id = sourceTaskId; return this.mutation<Generation>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/generations`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getGeneration(generationId: string): Promise<Generation> { return this.json<Generation>((await this.request("GET", `/v1/generations/${encodeURIComponent(generationId)}`)).body) }
  async listVariants(generationId: string, cursor?: string, limit = 50): Promise<Page<GenerationVariant>> { return this.page((await this.request("GET", `/v1/generations/${encodeURIComponent(generationId)}/variants?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getVariant(variantId: string): Promise<GenerationVariant> { return this.json<GenerationVariant>((await this.request("GET", `/v1/variants/${encodeURIComponent(variantId)}`)).body) }
  async createVariant(generationId: string, variantId: string, idempotencyKey: string, objectId?: string, variantType = "original", metadata: Record<string, unknown> = {}): Promise<MutationResult<GenerationVariant>> { const payload: Record<string, unknown> = { variant_id: variantId, variant_type: variantType, metadata }; if (objectId !== undefined) payload.object_id = objectId; return this.mutation<GenerationVariant>((await this.request("POST", `/v1/generations/${encodeURIComponent(generationId)}/variants`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
}
