import { describe, expect, it } from 'vitest';
import { isAutoGeneratedShortPrompt, toShortPrompt } from '../../lib/promptUtils';

describe('promptManagement utils', () => {
  it('creates truncated short prompt strings', () => {
    expect(toShortPrompt('short prompt')).toBe('short prompt');
    expect(toShortPrompt('abcdefghijklmnopqrstuvwxyz123456')).toBe('abcdefghijklmnopqrstuvwxyz1...');
  });

  it('detects generated short prompts with canonical and legacy rules', () => {
    const previousFullPrompt = 'abcdefghijklmnopqrstuvwxyz123456';
    const canonical = toShortPrompt(previousFullPrompt);
    const legacyBatch = `${previousFullPrompt.substring(0, 30)}...`;

    expect(isAutoGeneratedShortPrompt('', previousFullPrompt)).toBe(true);
    expect(isAutoGeneratedShortPrompt(canonical, previousFullPrompt)).toBe(true);
    expect(isAutoGeneratedShortPrompt(legacyBatch, previousFullPrompt)).toBe(true);
    expect(isAutoGeneratedShortPrompt('Custom label', previousFullPrompt)).toBe(false);
  });
});
