import { truncateText } from '@/shared/lib/stringFormatting';

const SHORT_PROMPT_MAX_LENGTH = 30;
const LEGACY_SHORT_PROMPT_PREFIX_LENGTH = 20;

/** Truncate a full prompt to a short display label (30 chars). */
export function toShortPrompt(fullPrompt: string): string {
  return truncateText(fullPrompt, SHORT_PROMPT_MAX_LENGTH);
}

function toLegacyBatchShortPrompt(fullPrompt: string): string {
  return fullPrompt.substring(0, SHORT_PROMPT_MAX_LENGTH)
    + (fullPrompt.length > SHORT_PROMPT_MAX_LENGTH ? '...' : '');
}

export function isAutoGeneratedShortPrompt(
  shortPrompt: string | undefined,
  previousFullPrompt: string,
): boolean {
  const normalizedShortPrompt = shortPrompt?.trim() ?? '';
  if (!normalizedShortPrompt) {
    return true;
  }

  if (normalizedShortPrompt === toShortPrompt(previousFullPrompt)) {
    return true;
  }

  if (normalizedShortPrompt === toLegacyBatchShortPrompt(previousFullPrompt)) {
    return true;
  }

  const legacyPrefix = previousFullPrompt.substring(0, LEGACY_SHORT_PROMPT_PREFIX_LENGTH);
  return legacyPrefix.length > 0 && normalizedShortPrompt.startsWith(legacyPrefix);
}
