// This file is automatically generated. Do not edit it directly.

import { createClient } from '@supabase/supabase-js';
import { handleError } from '@/shared/lib/errorHandler';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, __IS_DEV_ENV__, __WS_INSTRUMENTATION_ENABLED__, __REALTIME_DOWN_FIX_ENABLED__, __CORRUPTION_TRACE_ENABLED__ } from '@/integrations/supabase/config/env';
import { installWindowOnlyInstrumentation } from '@/integrations/supabase/instrumentation/window';
import { installRealtimeInstrumentation } from '@/integrations/supabase/instrumentation/realtime';
// Removed InstrumentationManager - system simplified
import { __CORRUPTION_TIMELINE__ } from '@/integrations/supabase/utils/timeline';
import { initAuthStateManager } from '@/integrations/supabase/auth/AuthStateManager';
import { getReconnectScheduler } from '@/integrations/supabase/reconnect/ReconnectScheduler';
import { maybeAutoLogin } from '@/integrations/supabase/dev/autoLogin';

// Install window-only instrumentation BEFORE any client creation
installWindowOnlyInstrumentation();

// Timeout configuration for network requests
const EDGE_FUNCTION_TIMEOUT_MS = 60000;
const STORAGE_UPLOAD_TIMEOUT_MS = 30000;
const REALTIME_HEARTBEAT_INTERVAL_MS = 30000;
const REALTIME_MAX_RECONNECT_DELAY_MS = 10000;

// Singleton pattern to prevent HMR-related duplicate declarations
// Store the client on window to avoid redeclaration errors during HMR
const getOrCreateSupabaseClient = (): ReturnType<typeof createClient<Database>> => {
  // Check if we already have a client from a previous module execution
  if (typeof window !== 'undefined' && window.__supabase_client__) {
    return window.__supabase_client__ as ReturnType<typeof createClient<Database>>;
  }

  let client: ReturnType<typeof createClient<Database>>;
  
  try {
    client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
      },
      realtime: {
        params: { eventsPerSecond: 10 },
        heartbeatIntervalMs: REALTIME_HEARTBEAT_INTERVAL_MS,
        reconnectAfterMs: (tries: number) => Math.min(tries * 1000, REALTIME_MAX_RECONNECT_DELAY_MS),
      },
      global: {
        fetch: (url: string, options: RequestInit = {}) => {
          const isEdgeFunction = url.includes('/functions/v1/');
          const isStorageUpload = url.includes('/storage/v1/object/');
          if (!isEdgeFunction && !isStorageUpload) {
            return fetch(url, options);
          }
          const controller = new AbortController();
          const timeoutMs = isEdgeFunction ? EDGE_FUNCTION_TIMEOUT_MS : STORAGE_UPLOAD_TIMEOUT_MS;
          const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
          let composedSignal = controller.signal;
          if (options.signal instanceof AbortSignal) {
            const existingSignal = options.signal;
            const composedController = new AbortController();
            const onAbort = () => composedController.abort();
            controller.signal.addEventListener('abort', onAbort);
            existingSignal.addEventListener('abort', onAbort);
            composedSignal = composedController.signal;
          }
          return fetch(url, { ...options, signal: composedSignal }).finally(() => clearTimeout(timeoutId));
        },
      },
      db: { schema: 'public' },
    });
  } catch (error: unknown) {
    handleError(error, { context: 'SupabaseClient', showToast: false });
    throw error;
  }

  // Store on window to reuse on HMR and for diagnostics
  if (typeof window !== 'undefined') {
    window.__supabase_client__ = client;
    window.supabase = client;
  }

  // Initialize centralized reconnect scheduler
  getReconnectScheduler();

  // Initialize centralized auth state manager
  initAuthStateManager(client);

  // Install realtime instrumentation after client creation
  installRealtimeInstrumentation(client);

  // Dev auto-login
  maybeAutoLogin(client);

  return client;
};

// Export the client directly from the function call
// This avoids top-level variable declarations that cause HMR issues
export const supabase = getOrCreateSupabaseClient();
