// This file is automatically generated. Do not edit it directly.

import { createClient } from '@supabase/supabase-js';
import { handleError } from '@/shared/lib/errorHandler';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, __IS_DEV_ENV__, __WS_INSTRUMENTATION_ENABLED__, __REALTIME_DOWN_FIX_ENABLED__, __CORRUPTION_TRACE_ENABLED__ } from '@/integrations/supabase/config/env';
import { installWindowOnlyInstrumentation } from '@/integrations/supabase/instrumentation/window';
import { installRealtimeInstrumentation } from '@/integrations/supabase/instrumentation/realtime';
// Removed InstrumentationManager - system simplified
import { captureRealtimeSnapshot } from '@/integrations/supabase/utils/snapshot';
import { __CORRUPTION_TIMELINE__ } from '@/integrations/supabase/utils/timeline';
import { initAuthStateManager } from '@/integrations/supabase/auth/AuthStateManager';
import { getReconnectScheduler } from '@/integrations/supabase/reconnect/ReconnectScheduler';
import { maybeAutoLogin } from '@/integrations/supabase/dev/autoLogin';

// Install window-only instrumentation BEFORE any client creation
installWindowOnlyInstrumentation();

// Singleton pattern to prevent HMR-related duplicate declarations
// Store the client on window to avoid redeclaration errors during HMR
const getOrCreateSupabaseClient = (): ReturnType<typeof createClient<Database>> => {
  // Check if we already have a client from a previous module execution
  if (typeof window !== 'undefined' && (window as any).__supabase_client__) {
    console.log('[Supabase] Reusing existing client from window (HMR reload detected)');
    return (window as any).__supabase_client__;
  }

  console.log('[Supabase] Creating new client');
  
  let client: ReturnType<typeof createClient<Database>>;
  
  try {
    client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
      },
      realtime: {
        params: { eventsPerSecond: 10 },
        heartbeatIntervalMs: 30000,
        reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 10000),
      },
      global: {
        fetch: (url: string, options: RequestInit = {}) => {
          const isEdgeFunction = url.includes('/functions/v1/');
          const isStorageUpload = url.includes('/storage/v1/object/');
          const isAuthRequest = url.includes('/auth/v1/');
          const isRestRequest = url.includes('/rest/v1/');
          if (!isEdgeFunction && !isStorageUpload) {
            return fetch(url, options);
          }
          const controller = new AbortController();
          const timeoutMs = isEdgeFunction ? 60000 : 30000;
          const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
          let composedSignal = controller.signal;
          if ((options as any).signal && 'signal' in options && (options as any).signal instanceof AbortSignal) {
            const existingSignal = (options as any).signal as AbortSignal;
            const composedController = new AbortController();
            const onAbort = () => composedController.abort();
            controller.signal.addEventListener('abort', onAbort);
            existingSignal.addEventListener('abort', onAbort);
            composedSignal = composedController.signal;
          }
          return fetch(url, { ...options, signal: composedSignal }).finally(() => clearTimeout(timeoutId));
        },
      },
      db: { schema: 'public' },
    });
  } catch (error: any) {
    handleError(error, { context: 'SupabaseClient', showToast: false });
    throw error;
  }

  // Store on window to reuse on HMR and for diagnostics
  if (typeof window !== 'undefined') {
    (window as any).__supabase_client__ = client;
    (window as any).supabase = client;
  }

  // Initialize centralized reconnect scheduler
  getReconnectScheduler();

  // Initialize centralized auth state manager
  initAuthStateManager(client);

  // Install realtime instrumentation after client creation
  installRealtimeInstrumentation(client);

  // Dev auto-login
  maybeAutoLogin(client);

  return client;
};

// Export the client directly from the function call
// This avoids top-level variable declarations that cause HMR issues
export const supabase = getOrCreateSupabaseClient();
