// This file is automatically generated. Do not edit it directly.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  __CORRUPTION_TRACE_ENABLED__,
  __IS_DEV_ENV__,
  __REALTIME_DOWN_FIX_ENABLED__,
  __WS_INSTRUMENTATION_ENABLED__,
} from '@/integrations/supabase/config/env';
import { installWindowOnlyInstrumentation } from '@/integrations/supabase/instrumentation/window';
import { __CORRUPTION_TIMELINE__ } from '@/integrations/supabase/utils/timeline';
import { createSupabaseClient } from '@/integrations/supabase/bootstrap/createSupabaseClient';
import { initializeSupabaseRuntime } from '@/integrations/supabase/bootstrap/initializeSupabaseRuntime';

// Install window-only instrumentation BEFORE any client creation
installWindowOnlyInstrumentation();

function registerSupabaseGlobals(client: ReturnType<typeof createClient<Database>>): void {
  if (typeof window === 'undefined') return;
  window.__supabase_client__ = client;
  window.supabase = client;
}

// Singleton pattern to prevent HMR-related duplicate declarations
// Store the client on window to avoid redeclaration errors during HMR
const getOrCreateSupabaseClient = (): ReturnType<typeof createClient<Database>> => {
  // Check if we already have a client from a previous module execution
  if (typeof window !== 'undefined' && window.__supabase_client__) {
    return window.__supabase_client__ as ReturnType<typeof createClient<Database>>;
  }

  const client = createSupabaseClient();

  // Store on window to reuse on HMR and for diagnostics
  registerSupabaseGlobals(client);

  initializeSupabaseRuntime(client);

  return client;
};

// Export the client directly from the function call
// This avoids top-level variable declarations that cause HMR issues
export const supabase = getOrCreateSupabaseClient();
